In [11]:
import pandas as pd
import zipfile
from pathlib import Path
data_folder = Path(r"C:/Users/traor/Documents/Case_Study/Cyclistic_Capstone/data/raw")
zip_files = sorted(data_folder.glob("*.zip"))

print(f"Number of ZIP files found: {len(zip_files)}")

for file in zip_files:
    print(file.name)

Number of ZIP files found: 12
202507-divvy-tripdata.zip
202508-divvy-tripdata.zip
202509-divvy-tripdata.zip
202510-divvy-tripdata.zip
202511-divvy-tripdata.zip
202512-divvy-tripdata.zip
202601-divvy-tripdata.zip
202602-divvy-tripdata.zip
202603-divvy-tripdata.zip
202604-divvy-tripdata.zip
202605-divvy-tripdata.zip
202606-divvy-tripdata.zip

In [13]:
dataframes = []

for zip_file in zip_files:

    with zipfile.ZipFile(zip_file, "r") as z:

        # Ignore macOS hidden files
        csv_name = [f for f in z.namelist()
                    if f.endswith(".csv") and "__MACOSX" not in f][0]

        df = pd.read_csv(z.open(csv_name))

        print(f"{csv_name}: {df.shape}")

        dataframes.append(df)

202507-divvy-tripdata.csv: (763432, 13)
202508-divvy-tripdata.csv: (790177, 13)
202509-divvy-tripdata.csv: (714759, 13)
202510-divvy-tripdata.csv: (646039, 13)
202511-divvy-tripdata.csv: (356628, 13)
202512-divvy-tripdata.csv: (140534, 13)
202501-divvy-tripdata.csv: (137787, 13)
202602-divvy-tripdata.csv: (201450, 13)
202603-divvy-tripdata.csv: (317037, 13)
202604-divvy-tripdata.csv: (448252, 13)
202605-divvy-tripdata.csv: (653704, 13)
202606-divvy-tripdata.csv: (762550, 13)

In [14]:
columns_match = all(
    df.columns.equals(dataframes[0].columns)
    for df in dataframes
)

print("All files have identical columns:", columns_match)

All files have identical columns: True

In [15]:
combined_df = pd.concat(
    dataframes,
    ignore_index=True
)

In [16]:
print("Shape:", combined_df.shape)

combined_df.head()

Shape: (5932349, 13)

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,455D43BD91D73437,classic_bike,2025-07-05 17:15:08.456,2025-07-05 17:25:47.079,Lincoln Ave & Diversey Pkwy,CHI00285,Lincoln Ave & Addison St,CHI00478,41.932225,-87.658617,41.946176,-87.673308,member
1,9D4A6B723ECD98CA,classic_bike,2025-07-01 13:57:38.878,2025-07-01 14:06:35.780,Cottage Grove Ave & Oakwood Blvd,CHI00400,Cottage Grove Ave & 47th St,CHI00488,41.822985,-87.607100,41.809855,-87.606755,member
2,C57044CF523302ED,classic_bike,2025-07-31 16:49:28.142,2025-07-31 17:15:28.999,Theater on the Lake,CHI00420,Winthrop Ave & Lawrence Ave,CHI00391,41.926277,-87.630834,41.968812,-87.657659,member
3,AFD35552E6685B6E,electric_bike,2025-07-17 09:36:21.058,2025-07-17 09:46:54.706,Pine Grove Ave & Waveland Ave,CHI00354,Winthrop Ave & Lawrence Ave,CHI00391,41.949473,-87.646453,41.968812,-87.657659,member
4,C0582EBAA6CED519,classic_bike,2025-07-02 18:43:45.213,2025-07-02 18:57:06.687,Theater on the Lake,CHI00420,Sheffield Ave & Wellington Ave,CHI00274,41.926277,-87.630834,41.936253,-87.652662,member

In [17]:
cleaned_folder = Path(r"C:/Users/traor/Documents/Case_Study/Cyclistic_Capstone/data/cleaned")
cleaned_folder.mkdir(parents=True, exist_ok=True)

In [18]:
combined_df.to_csv(
    cleaned_folder / "cyclistic_combined.csv",
    index=False
)

print("Combined dataset saved successfully!")

Combined dataset saved successfully!

In [19]:
combined_df.shape

(5932349, 13)

In [20]:
combined_df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,455D43BD91D73437,classic_bike,2025-07-05 17:15:08.456,2025-07-05 17:25:47.079,Lincoln Ave & Diversey Pkwy,CHI00285,Lincoln Ave & Addison St,CHI00478,41.932225,-87.658617,41.946176,-87.673308,member
1,9D4A6B723ECD98CA,classic_bike,2025-07-01 13:57:38.878,2025-07-01 14:06:35.780,Cottage Grove Ave & Oakwood Blvd,CHI00400,Cottage Grove Ave & 47th St,CHI00488,41.822985,-87.607100,41.809855,-87.606755,member
2,C57044CF523302ED,classic_bike,2025-07-31 16:49:28.142,2025-07-31 17:15:28.999,Theater on the Lake,CHI00420,Winthrop Ave & Lawrence Ave,CHI00391,41.926277,-87.630834,41.968812,-87.657659,member
3,AFD35552E6685B6E,electric_bike,2025-07-17 09:36:21.058,2025-07-17 09:46:54.706,Pine Grove Ave & Waveland Ave,CHI00354,Winthrop Ave & Lawrence Ave,CHI00391,41.949473,-87.646453,41.968812,-87.657659,member
4,C0582EBAA6CED519,classic_bike,2025-07-02 18:43:45.213,2025-07-02 18:57:06.687,Theater on the Lake,CHI00420,Sheffield Ave & Wellington Ave,CHI00274,41.926277,-87.630834,41.936253,-87.652662,member

In [21]:
combined_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5932349 entries, 0 to 5932348
Data columns (total 13 columns):
 #   Column              Dtype
---  ------              -----
 0   ride_id             str
 1   rideable_type       str
 2   started_at          str
 3   ended_at            str
 4   start_station_name  str
 5   start_station_id    str
 6   end_station_name    str
 7   end_station_id      str
 8   start_lat           float64
 9   start_lng           float64
 10  end_lat             float64
 11  end_lng             float64
 12  member_casual       str
dtypes: float64(4), str(9)
memory usage: 588.4 MB

In [22]:
combined_df.isnull().sum()

ride_id                     0
rideable_type               0
started_at                  0
ended_at                    0
start_station_name    1257513
start_station_id      1257513
end_station_name      1321680
end_station_id        1321680
start_lat                   0
start_lng                   0
end_lat                  5606
end_lng                  5606
member_casual               0
dtype: int64

In [23]:
combined_df["ride_id"].duplicated().sum()

np.int64(35)

In [24]:
combined_df.head(100).to_csv(
    "sample_cyclistic.csv",
    index=False
)